#!/bin/env bash

#
# Copies dotfiles from ~/dot to proper locations
# Saves old dotfiles (if present) to ~/dot_old
#

cd
DIR=~/dot

[ -d ~/dot_old ] || mkdir -p ~/dot_old/{bspwm/firefox/git/panel/sxhkd/x/zsh}

OLD=~/dot_old


#bspwm
    [ -d ~/.config/bspwm/ ] && mv ~/.config/bspwm/* ~/dot_old/bspwm/
    ln -s $DIR/bspwm/bspwmrc ~./config/bspwm/bcpwmrc

#firefox
    FFPROFILE=$(ls -td ~/.mozilla/firefox/*/ | head -1)
    [ -d $FFPROFILE/chrome/userChrome.css ] mv $FFPROFILE/chrome/userChrome.css $OLD/firefox/
    ln -s $DIR/firefox/userChrome.css ~/.mozilla/firefox/$FFPROFILE/chrome/userChrome.css
  #vimperator
    [ -f ~/.vimperatorrc ] && mv ~/.vimperatorrc $OLD/firefox/
    ln -s $DIR/firefox/vimperatorrc .vimperatorrc
#git
    [ -f ~/.gitconfig ] && mv ~/.gitconfig $OLD/git/
    ln -s $DIR/git/gitconfig ~/.gitconfig

#panel
    [ -d ~/.config/panel/ ] && mv ~/.config/panel/* $OLD/panel/
    ln -s $DIR/panel/panel ~./config/panel/panel
    ln -s $DIR/panel/panel_bar ~./config/panel/panel_bar
    ln -s $DIR/panel/panel_colors ./config/panel/panel_colors

#sxhkd
    [ -d ~/.config/sxhkd/ ] && mv ~/.config/sxhkd/* $OLD/sxhkd/
    ln -s $DIR/sxhkd/sxhkdrc ~./config/sxhkd/sxhkdrc

#x
    [ -f ~/.Xdefaults ] && mv ~/.Xdefaults $OLD/x/ 
    ln -s $DIR/x/Xdefaults .Xdefaults

    [ -f ~/.xinitrc ] && mv ~/.xinitrc $OLD/x/
    ln -s $DIR/x/xinitrc .xinitrc
#zsh
    [ -f ~/.zshrc ] && mv ~/.xinitrc $old/zsh/
    ln -s $DIR/zsh .zshrc

#delete empty config directories
    find $OLD -type d -empty -delete

