# Lines configured by zsh-newuser-install
	HISTFILE=~/.histfile
	HISTSIZE=1000
	SAVEHIST=1000
	setopt appendhistory extendedglob nomatch notify
	unsetopt beep
	bindkey -v

# The following lines were added by compinstall
	zstyle :compinstall filename '/home/void/.zshrc'
	autoload -Uz compinit
	compinit

# Set PS1
	PS1='[%n@%m %~]%# '

# Path configuration
	typeset -U path
	path+=(/home/void/bin)
	path+=(/home/void/.config/panel)

# Set editor
	export EDITOR=vim

# Set Arch blue
#	export ARCH_BLUE=#1793D1

# BAR settings
	export PANEL_FIFO="/tmp/panel-fifo"
	PANEL_HEIGHT=18
	PANEL_FONT_FAMILY="-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-1"
	export PANEL_FIFO PANEL_HEIGHT PANEL_FONT_FAMILY

# Aliases
	alias x='startx'
	alias xumf='sudo netctl start eduroam && x'
	alias ls='ls --color=auto'
	alias please='sudo $(fc -ln -1)'
	alias sd='sudo shutdown now'
	alias pingg='ping -c 3 www.google.com'
	alias dbox='dropbox-cli'
	alias ipld='sudo ip link set wlp3s0 down'
	alias xe='journalctl -xe'
	alias jflap='java -jar /home/void/dropbox/umf/2015.4/csc381/JFLAP.jar'

	alias win='virtualbox --startvm win7 --fullscreen'

	alias umf='cd /home/void/dropbox/umf/2015.4/'
	alias cdrp='cd /home/void/dropbox/umf/2015.4/csc446/rp/'

	alias duk='du --block-size=KiB --max-depth=1 | sort -n' 
	alias dum='du --block-size=MiB --max-depth=1 | sort -n'    
	alias dug='du --block-size=GiB --max-depth=1 | sort -n'

	alias waka='pacaur -Syu --noedit'
	alias wakawaka='pacaur -Syu --noconfirm --noedit'

	alias cal='cal -m'

# Other settings
#	setxkbmap -option compose:caps
		#throws "default display" error; doesn't work in .xinitrc
		#TODO: find another file to source
