# Lines configured by zsh-newuser-install
	HISTFILE=~/.histfile
	HISTSIZE=1000
	SAVEHIST=1000
	setopt appendhistory extendedglob nomatch notify
	unsetopt beep
	bindkey -v

# The following lines were added by compinstall
	zstyle :compinstall filename '/home/void/.zshrc'
	autoload -Uz compinit
	compinit

# Set PS1
	PS1='[%n@%m %~]%# '

# Path configuration
	typeset -U path
	path+=(/home/void/.bin)
	path+=(/home/void/.config/panel)

# Set editor
	export EDITOR=vim

# Set Arch blue
#	export ARCH_BLUE=#1793D1

# lemonbar settings
	export PANEL_FIFO="/tmp/panel-fifo"
	PANEL_HEIGHT=16
	PANEL_FONT_FAMILY="-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-1"
	export PANEL_FIFO PANEL_HEIGHT PANEL_FONT_FAMILY

# Aliases
	alias x='startx'
	alias ssh='ssh -L 5901:localhost:5901'
	alias sshh='ssh -Y -p 30622 mirrodin.protoco.de'
	alias internet='sudo netctl stop-all && sudo netctl start'
	alias i='internet'
	alias xumf='sudo netctl start eduroam && x'
	alias xamber='sudo netctl start ATT7Y9xcn4 && x'
	alias ls='ls --color=auto'
	alias please='sudo $(fc -ln -1)'
	alias sd='sudo shutdown now'
	alias ds='sudo shutdown now'
	alias pinga='ping -c 3 www.archlinux.org'
	alias dbox='dropbox-cli'
	alias ipld='sudo ip link set wlp3s0 down'
	alias xe='journalctl -xe'

	alias duk='du --block-size=KiB --max-depth=1 | sort -n' 
	alias dum='du --block-size=MiB --max-depth=1 | sort -n'    
	alias dug='du --block-size=GiB --max-depth=1 | sort -n'

	alias waka='pacaur -Syu --noedit'
	alias wakawaka='pacaur -Syu --noconfirm --noedit'

	alias cal='cal -m'
	alias win='rdesktop -g 1600x900 -K -P -z -x l -r sound:off -u void mirrodin.protoco.de:3389' 
	alias steam2="LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so' /usr/bin/steam"

# fix the internet!
#ipld
